version: '3.6'

services:

  pgs-local:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432